project_id = "ncdhbxracduskwrberpl"

[functions.chat]
verify_jwt = true

[functions.discover]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

[functions.generate-code]
verify_jwt = true

[functions.ai-suggest]
verify_jwt = true
